//users
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const DELETE_USER_SUCCES = "DELETE_USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";

//errors
export const SET_ERROR = "SET_ERROR";
export const HIDE_ERROR = "HIDE_ERROR";

//fetching 
export const SET_FETCHING = "SET_FETCHING";
export const UNSET_FETCHING = "UNSET_FETCHING";

//products
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const DELETE_PRODUCT_SUCCES = "DELETE_PRODUCT_SUCCESS";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const DELETE_CATEGORY_SUCCES = "DELETE_CATEGORY_SUCCES";
export const PRODUCT_ERROR = "PRODUCT_ERROR";

