//users
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const DELETE_USER_SUCCES = "DELETE_USER_SUCCESS";
export const EDIT_USER_SUCCES = "EDIT_USER_SUCCESS";
export const USER_ERROR = "USER_ERROR";
export const SET_FETCHING_USER = "SET_FETCHING_USER";
export const UNSET_FETCHING_USER = "UNSET_FETCHING_USER";

//errors
export const SET_ERROR = "SET_ERROR";
export const HIDE_ERROR = "HIDE_ERROR";

//fetching 
export const SET_FETCHING = "SET_FETCHING";
export const UNSET_FETCHING = "UNSET_FETCHING";

//products
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const DELETE_PRODUCT_SUCCES = "DELETE_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_SUCCES = "EDIT_PRODUCT_SUCCESS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const SET_FETCHING_PRODUCT = "SET_FETCHING_PRODUCT";
export const UNSET_FETCHING_PRODUCT = "UNSET_FETCHING_PRODUCT";


//categories
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const EDIT_CATEGORY_SUCCES = "EDIT_CATEGORY_SUCCESS";
export const CATEGORY_ERROR = "CATEGORY_ERROR";
export const SET_FETCHING_CATEGORY = "SET_FETCHING_CATEGORY";
export const UNSET_FETCHING_CATEGORY = "UNSET_FETCHING_CATEGORY";

//endpoints
export const PRODUCTS = "products";
export const CATEGORIES = "categories";
export const USERS = "users";



